// Type definitions for the prompt generator

// Age is now a number input field
export type Age = number;

export type Gender = 'male' | 'female';

// Comprehensive list of all nationalities (sorted alphabetically)
export const ALL_NATIONALITIES: string[] = [
  'African American',
  'Albanian',
  'Algerian',
  'American',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Aymara',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Belarusian',
  'Black American',
  'Bosnian',
  'Botswanan',
  'Brazilian',
  'Bulgarian',
  'Burkina Faso',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Central African',
  'Chadian',
  'Chechen',
  'Chilean',
  'Chinese',
  'Colombian',
  'Congolese',
  'Croatian',
  'Czech',
  'Dagestani',
  'Danish',
  'Djiboutian',
  'Dutch',
  'Ecuadorian',
  'Emirati',
  'English',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Gabonese',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Guarani',
  'Guinean',
  'Guyanese',
  'Haitian',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indigenous South American',
  'Indonesian',
  'Iranian',
  'Irish',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakh',
  'Kenyan',
  'Korean',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Libyan',
  'Lithuanian',
  'Malaysian',
  'Malian',
  'Mauritanian',
  'Mestizo',
  'Mixed Latin American',
  'Mixed Race',
  'Moldovan',
  'Montenegrin',
  'Mongolian',
  'Multiracial',
  'Myanmar',
  'Namibian',
  'Nepalese',
  'New Zealander',
  'Nigerian',
  'Nigerien',
  'North Korean',
  'North Macedonian',
  'Norwegian',
  'Omani',
  'Palestinian',
  'Papua New Guinean',
  'Paraguayan',
  'Persian',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Quechua',
  'Romanian',
  'Russian',
  'Rwandan',
  'Samoan',
  'Saudi Arabian',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Korean',
  'Spanish',
  'Sri Lankan',
  'Staff',
  'Swedish',
  'Swiss',
  'Syrian',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Tongan',
  'Trinidadian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Vietnamese',
  'Welsh',
  'White American',
  'White Canadian',
  'Zimbabwean',
].sort();

// Hair options by gender
export const HAIR_OPTIONS_MALE = [
  'short fade',
  'buzz cut',
  'curly crop',
  'textured fringe',
  'classic side part',
  'messy medium',
] as const;

export const HAIR_OPTIONS_FEMALE = [
  'tied-back ponytail',
  'low bun',
  'shoulder-length straight',
  'wavy medium',
  'short bob',
  'slicked-back',
] as const;

// Facial hair options (male only)
export const FACIAL_HAIR_OPTIONS = [
  'clean-shaven',
  'light stubble',
  'short beard',
  'trimmed goatee',
] as const;

// Expression options (database style)
export const EXPRESSION_OPTIONS = [
  'neutral and calm',
  'neutral with slight intensity',
  'calm, focused, mouth closed',
  'subtle confident look, no smile',
] as const;

// Facial structure options
export const FACIAL_STRUCTURE_OPTIONS = [
  'lean defined jawline',
  'more oval face',
  'slightly wider jaw',
  'prominent cheekbones',
  'narrower chin',
] as const;

// Skin detail options
export const SKIN_DETAIL_OPTIONS = [
  'pores + mild blemishes',
  'visible freckles',
  'mild acne',
  'under-eye texture',
  'slight redness around nose/cheeks',
] as const;

// Eyebrow options
export const EYEBROW_OPTIONS = ['thin', 'medium', 'thick'] as const;

// Nose shape options
export const NOSE_OPTIONS = ['straight', 'slightly curved', 'narrow', 'broad'] as const;

// Ear prominence options
export const EAR_OPTIONS = ['subtle', 'moderate', 'prominent'] as const;
